name: Superenalotto Armonia 137 Update

on:
  schedule:
    # Esecuzione alle 20:30 UTC (circa 22:30 ora italiana) 
    # nei giorni di estrazione: Martedì, Giovedì, Venerdì, Sabato.
    - cron: '30 20 * * 2,4,5,6'
  workflow_dispatch: # Permette l'avvio manuale dal tasto "Run workflow"

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installa Dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install pandas supabase requests numpy beautifulsoup4

      - name: Esecuzione Update Database
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python update_estrazioni.py
